name: Update Documentation

on: [workflow_dispatch]

jobs:
  build:
    name: Create Documentation
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Git Identity
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Pull Git Subtree
      run: |
        git subtree pull --prefix Documentation/_site origin gh-pages
        git add Documentation/_site/** -f
        git commit

    - name: Dotnet Build
      run: dotnet build -c Documentation

    - name: Save Documentation
      run: |
        git add Documentation/_site/** -f
        git commit -m "Update content of .NET SDK documentation on GitHub Pages web site."

    - name: Push Git Subtree
      run: |
        git subtree push --prefix Documentation/_site origin gh-pages
        git push origin
